### ISSUE TITLE
Adding visualizer classes to __init__ forces to install `pyqt5`, etc.

### ISSUE THREAD

**Issue by delaossa** [AngelFP/VisualPIC#41]
Calling the classes `VTKVisualizer` and `MplVisualizer` in __init__.py :
https://github.com/AngelFP/VisualPIC/blob/18245da9ce2a3d1eded8bc7df28ca02dfa9255a4/visualpic/__init__.py#L6
will force you to install the extra packages that they need (pyqt5, vtk, pyvista).
Otherwise a `ModuleNotFoundError` will be thrown.

**Comment by AngelFP** [comment]
Thanks @delaossa! This should fix it (#42). I think the issue was only with `pyqt5` (due to the new `MplVisualizer`). The `VTKVisualizer` has been in the `__init__.py` for a long time now without issues.

**Comment by delaossa** [comment]
Thank you @AngelFP ! 👍
